spring:
 application:
  name: gastos-service
 jpa:
  database: MYSQL
  show-sql: true
  properties:
   hibernate:
    ddl-auto: none
 datasource:
  url: jdbc:mysql://localhost:3306/dbgastos?useTimezone=true&serverTimezone=UTC
  username: root
  password: admin

server:
 port: 9092

eureka:
 client:
  service-url:
   default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
   prefer-ip-address: true
