spring:
 application:
  name: API-GATEWAY

server:
 port: 8080

eureka:
 client:
  service-url:
   default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
 instance:
  prefer-ip-adress: true

zuul:
 ignoredServices: '*'
 prefix: /api
 routes:
  gastos-service:
   path: /gastos/**
   strip-prefix: false
   serviceId: GASTOS-SERVICE